version: '3.8'
services:
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - '27017:27017'
  api:
    image: node:slim
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: "npm run start"
